---
- name: Contrôle de santé
  hosts: localhost
  tasks:
    - name: "Attendre que NiceGUI réponde sur 8081"
      uri:
        url: "http://localhost:8081"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 20      # Important : NiceGUI est lent à démarrer
      delay: 5
